components:
- description: ''
  instances: [
    ]
  name: Eureka Service Discovery
  tags: [
    ]
- description: ''
  instances: [
    ]
  name: Git Repo
  tags: [
    ]
- description: ''
  instances: [
    ]
  name: Spring Boot Admin Server
  tags: [
    ]
- description: ''
  instances: [
    ]
  name: Spring Cloud Config Server
  tags: [
    ]
- description: ''
  instances:
  - coverage:
      agentUrl: http://api-gateway:8050
      buildId: spring-petclinic-api-gateway-2026-02-10
      coverageImages: spring-petclinic-api-gateway;spring-petclinic-api-gateway-FT
      dtpFilter: null
      dtpProject: spring-petclinic-api-gateway
    description: ''
    name: Local Gateway
  name: UI + API Gateway
  tags: [
    ]
- description: ''
  instances: [
    ]
  name: Web Browser
  tags: [
    ]
- description: ''
  instances: [
    ]
  name: Zipkin Distributed Logging Server
  tags: [
    ]
- description: ''
  instances:
  - coverage:
      agentUrl: http://customers-service:8050
      buildId: spring-petclinic-customers-service-2026-02-10
      coverageImages: spring-petclinic-customers-service;spring-petclinic-customers-service-FT
      dtpFilter: null
      dtpProject: spring-petclinic-customers-service
    description: ''
    name: Customers Microservice
  name: customers-service REST API
  tags: [
    ]
- description: ''
  instances: [
    ]
  name: customers-storage
  tags: [
    ]
- description: ''
  instances:
  - coverage:
      agentUrl: http://vets-service:8050
      buildId: spring-petclinic-vets-service-2026-02-10
      coverageImages: spring-petclinic-vets-service;spring-petclinic-vets-service-FT
      dtpFilter: null
      dtpProject: spring-petclinic-vets-service
    description: ''
    name: Vets Microservice
  name: vets-service REST API
  tags: [
    ]
- description: ''
  instances: [
    ]
  name: vets-storage
  tags: [
    ]
- description: ''
  instances:
  - coverage:
      agentUrl: http://visits-service:8050
      buildId: spring-petclinic-visits-service-2026-02-10
      coverageImages: spring-petclinic-visits-service;spring-petclinic-visits-service-FT
      dtpFilter: null
      dtpProject: spring-petclinic-visits-service
    description: ''
    name: Visits Microservice
  name: visits-service REST API
  tags: [
    ]
- description: ''
  instances: [
    ]
  name: visits-storage
  tags: [
    ]
description: Each microservice points to a different DTP project.
name: Multi Repo PetClinic Example
tags: [
  ]