components:
- description: ''
  instances: [
    ]
  name: Eureka Service Discovery
  tags: [
    ]
- description: ''
  instances: [
    ]
  name: Git Repo
  tags: [
    ]
- description: ''
  instances: [
    ]
  name: Spring Boot Admin Server
  tags: [
    ]
- description: ''
  instances: [
    ]
  name: Spring Cloud Config Server
  tags: [
    ]
- description: ''
  instances:
  - coverage:
      agentUrl: http://api-gateway:8050
      buildId: spring-petclinic-microservices-baseline
      coverageImages: spring-petclinic-microservices;spring-petclinic-microservices-FT
      dtpFilter: null
      dtpProject: spring-petclinic-microservices
    description: ''
    name: Local Gateway
  name: UI + API Gateway
  tags: [
    ]
- description: ''
  instances: [
    ]
  name: Web Browser
  tags: [
    ]
- description: ''
  instances: [
    ]
  name: Zipkin Distributed Logging Server
  tags: [
    ]
- description: ''
  instances:
  - coverage:
      agentUrl: http://customers-service:8050
      buildId: spring-petclinic-microservices-baseline
      coverageImages: spring-petclinic-microservices;spring-petclinic-microservices-FT
      dtpFilter: null
      dtpProject: spring-petclinic-microservices
    description: ''
    name: Customers Microservice
  name: customers-service REST API
  tags: [
    ]
- description: ''
  instances: [
    ]
  name: customers-storage
  tags: [
    ]
- description: ''
  instances:
  - coverage:
      agentUrl: http://vets-service:8050
      buildId: spring-petclinic-microservices-baseline
      coverageImages: spring-petclinic-microservices;spring-petclinic-microservices-FT
      dtpFilter: null
      dtpProject: spring-petclinic-microservices
    description: ''
    name: Vets Microservice
  name: vets-service REST API
  tags: [
    ]
- description: ''
  instances: [
    ]
  name: vets-storage
  tags: [
    ]
- description: ''
  instances:
  - coverage:
      agentUrl: http://visits-service:8050
      buildId: spring-petclinic-microservices-baseline
      coverageImages: spring-petclinic-microservices;spring-petclinic-microservices-FT
      dtpFilter: null
      dtpProject: spring-petclinic-microservices
    description: ''
    name: Visits Microservice
  name: visits-service REST API
  tags: [
    ]
- description: ''
  instances: [
    ]
  name: visits-storage
  tags: [
    ]
description: All microservices point to the same DTP project.
name: Single Repo PetClinic Example
tags: [
  ]