apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.vets.name | quote }}
  labels:
    app: {{ .Values.app.name | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app.name | quote }}
      microservice: {{ .Values.vets.name | quote }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name | quote }}
        microservice: {{ .Values.vets.name | quote }}
    spec:
      containers:
      - name: {{ .Values.vets.name | quote }}
        image: harbor.parasoft.com/ctp/springcommunity/spring-petclinic-vets-service:latest
        imagePullPolicy: Always
        command: ["./dockerize"]
        args: ["-wait=tcp://{{ .Values.discovery.service.name }}:{{ .Values.discovery.service.port }}", "-timeout=60s", "--", "java", "org.springframework.boot.loader.JarLauncher"]
        ports:
        - containerPort: {{ .Values.vets.containerPort }}
        - containerPort: {{ .Values.vets.covagents.port }}
        env:
        - name: eureka.instance.hostname
          value: {{ .Values.vets.service.name | quote }}
        - name: management.zipkin.tracing.endpoint
          value: http://{{ .Values.tracing.service.name }}:{{ .Values.tracing.service.port }}/api/v2/spans
        - name: JDK_JAVA_OPTIONS
          value: "-javaagent:{{ .Values.vets.covagents.mountPath }}/agent.jar=settings={{ .Values.vets.config.mountPath }}/agent.properties"
        volumeMounts:
        - name: {{ .Values.vets.volume.name | quote }}
          mountPath: {{ .Values.vets.covagents.mountPath }}
        - name: {{ .Values.vets.config.name | quote }}
          mountPath: {{ .Values.vets.config.mountPath }}
      initContainers:
      - name: {{ .Values.vets.init.name | quote }}
        image: harbor.parasoft.com/ctp/java-coverage-init-container:latest
        command: ['sh', '-c', 'cp /agent/*.jar {{ .Values.vets.init.mountPath }}/']
        volumeMounts:
        - name: {{ .Values.vets.volume.name | quote }}
          mountPath: {{ .Values.vets.init.mountPath }}      
      {{ if .Values.images.auth }}
      imagePullSecrets:
      - name: {{ .Values.images.secret | quote }}
      {{ end }}
      volumes:
      - name: {{ .Values.vets.volume.name | quote }}
        emptyDir: {}
      - name: {{ .Values.vets.config.name | quote }}
        configMap:
          name: {{ .Values.vets.config.name | quote }}
          items:
          - key: "agent.properties"
            path: "agent.properties"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.vets.config.name | quote }}
data:
  agent.properties: {{ .Values.vets.config.properties | toYaml | indent 1 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.vets.service.name | quote }}
spec:
  ports:
  - port: {{ .Values.vets.service.port }}
    protocol: TCP
    targetPort: {{ .Values.vets.containerPort }}
  selector:
    app: {{ .Values.app.name | quote }}
    microservice: {{ .Values.vets.name | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.vets.covagents.service.name | quote }}
spec:
  ports:
  - port: {{ .Values.vets.covagents.service.port }}
    protocol: TCP
    targetPort: {{ .Values.vets.covagents.port }}
  selector:
    app: {{ .Values.app.name | quote }}
    microservice: {{ .Values.vets.name | quote }}
