<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.springframework.samples.petclinic.selenium</groupId>
    <artifactId>spring-petclinic-selenium-testng-tests</artifactId>
    <packaging>jar</packaging>
    <description>Spring PetClinic Selenium TestNG Tests</description>

    <parent>
        <groupId>org.springframework.samples</groupId>
        <artifactId>spring-petclinic-microservices</artifactId>
        <version>3.0.9</version>
    </parent>

    <properties>
        <testng.version>7.12.0</testng.version>
        <selenium.version>4.40.0</selenium.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.samples.petclinic.testcommon</groupId>
            <artifactId>spring-petclinic-testcommon</artifactId>
            <version>1.0.0</version>
        </dependency>
        
        <!-- Web UI Testing -->
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>${selenium.version}</version>
            <scope>test</scope>
        </dependency>
        
        <!-- Test Framework -->
        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>${testng.version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <!-- Use Failsafe for functional/integration tests -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>3.5.4</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <includes>
                        <include>**/*IT.java</include>
                        <include>**/*ITCase.java</include>
                    </includes>
                    <providers>
                        <provider>
                            <name>testng</name>
                        </provider>
                    </providers>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
