apiVersion: apps/v1
kind: Deployment
metadata:
  name: visits-service
  labels:
    app: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic
      microservice: visits-service
  template:
    metadata:
      labels:
        app: petclinic
        microservice: visits-service
    spec:
      containers:
      - name: visits-service
        image: harbor.parasoft.com/ctp/springcommunity/spring-petclinic-visits-service:latest
        imagePullPolicy: Always
        command: ["./dockerize"]
        args: ["-wait=tcp://discovery-server:8761", "-timeout=60s", "--", "java", "org.springframework.boot.loader.JarLauncher"]
        ports:
        - containerPort: 8082
        - containerPort: 8050
        env:
        - name: eureka.instance.hostname
          value: visits-service
        - name: management.zipkin.tracing.endpoint
          value: http://tracing-server:9411/api/v2/spans 
        - name: JDK_JAVA_OPTIONS
          value: "-javaagent:/tmp/coverage/agent.jar=settings=/config/agent.properties"
        volumeMounts:
        - name: visits-service-volume
          mountPath: /tmp/coverage
        - name: visits-service-configmap
          mountPath: /config
      initContainers:
      - name: java-coverage-agent
        image: harbor.parasoft.com/ctp/java-coverage-init-container:latest
        command: ['sh', '-c', 'cp /agent/*.jar /tmp/coverage/']
        volumeMounts:
        - name: visits-service-volume
          mountPath: /tmp/coverage
      volumes:
      - name: visits-service-volume
        emptyDir: {}
      - name: visits-service-configmap
        configMap:
          name: visits-service-configmap
          items:
          - key: "agent.properties"
            path: "agent.properties"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: visits-service-configmap
data:
  # Use below to configure the Coverage Agent for this Microservice
  agent.properties: |
    jtest.agent.runtimeData=runtime_coverage
    jtest.agent.includes=org/springframework/samples/**
    jtest.agent.autostart=false
    jtest.agent.port=8050
---
apiVersion: v1
kind: Service
metadata:
  name: visits-service
spec:
  ports:
  - port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    app: petclinic
    microservice: visits-service
---
apiVersion: v1
kind: Service
metadata:
  name: visits-service-coverage-agent
spec:
  ports:
  - port: 8050
    protocol: TCP
    targetPort: 8050
  selector:
    app: petclinic
    microservice: visits-service
